# In this notebook, we'are going to cover some fundamental concepts of tensorflow
1. Introduction to the tensors
2. Getting information from tensors
3. Manipulating tensors
3. Tensors & Numpy 
4. Using @tf.function(a way to speed up our regular python functions)
5. Using GPUs with TensorFlow(or TPUs)
6. Exercises to try yourself

## Introductions to Tensors

What we will study below:-
1. Scaler: A single number
2. Vector: A number with direction
3. Matrix: a 2-Dimenstional array of numbers
4. Tensor: an n-dimensional array of numbers





In [1]:
import numpy as np

In [2]:
import tensorflow as tf
print(tf.__version__) #Finding the version of tensorflow version

2.5.0


Create Tensors with tf.constant()

In [3]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

**Creating 1-D tensor from a python list**

In [4]:
tf.constant([1,2,3,4,5])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

**From a numpy array**

In [5]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

**We can also specify dtype of tensor values**

In [7]:
tf.constant([1,1,5,6,3,6],dtype=tf.float64)

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([1., 1., 5., 6., 3., 6.])>

If **shape** is set, the value is reshaped to match, scalers are expanded to fill the shape

In [8]:
tf_array=tf.constant(0,shape=(2,3))

In [9]:
tf_array

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [10]:
tf.constant([1,2,3,4,5,6],shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

**Types of error that can occure**
1. TypeError:- if shape is incorrectly specified or unsupported
2. ValueError:- If tf.constant called on symbolic tensor

checking the dimensions of a tensor(ndim stands for number of dimensions)

In [11]:
tf_matrix=tf.constant(0,shape=(2,3))
tf_matrix.ndim

2

In [12]:
another_matrix = tf.constant([[[1,2,3],[4,5,6]],[[5,6,3],[0,4,1]]])
another_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 3],
        [0, 4, 1]]], dtype=int32)>

In [13]:
another_matrix.ndim

3

## Creating tensors with tensorflow and tf.Variable

A variable maintains shared, persistent state manipulated by a program.

The Variable() constructor requires an initial value for the variable, which
can be a Tensor of any type and shape. This initial value defines the type
and shape of the variable. After construction, the type and shape of the
variable are fixed. The value can be changed using one of the assign methods.

Create the tensor with tf.Variable()

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.Variable([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
changeable_tensor[0]=12

TypeError: ignored

How abour we try .assign() methoda as per documentation

In [ ]:
changeable_tensor[0].assign(12)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>

In [ ]:
unchangeable_tensor.assign(9)

ValueError: ignored

## Creating random tensors


Creating two random(but the same) tensors

In [37]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [38]:
random_2 = tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

are the equal

In [39]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Suffling the order of elements in a tensors
Shuffle a tensor (valuable for when we want to shuffle our data so the inherent order doesn't effect learning

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [4,5],
                            [3,1]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5],
       [ 3,  1]], dtype=int32)>

**Shuffle our not_shuffled tensor**

In [ ]:
tf.random.shuffle(value=not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  1],
       [ 4,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(value=not_shuffled,seed=2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5],
       [ 3,  1]], dtype=int32)>

You can also set seed using tf.random.set_seed(42)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(value=not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 3,  1],
       [10,  7]], dtype=int32)>

## Global level random seed and operational level random seed
It looks like if we want our shuffled tensors to be in the same orderm we've got to use the global level random seed as well as the operational level random seed
Rule4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."
[https://www.tensorflow.org/api_docs/python/tf/random/set_seed](https://)

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) #operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5],
       [ 3,  1]], dtype=int32)>

## Creating tensors from Numpy arrays

Other ways to make tensors

In [ ]:
#Create a tensor of all 
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeros
tf.zeros(shape=(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

Turn NumPy arrays into tensors
1. The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU(Much Faster for numerical Computation)

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)

In [ ]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(value=numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
#creating the 3 dimensional matrix
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Shape must be like 2*3*4=len(numpy vector)

## Getting Information From Your tensors
1. Shape -- the length(number of elements) of each of the dimensions of a tensor **code-tensor.ndim**
2. Rank  -- The number of tensor dimensions. A scaler has rank 0, a vector has rank 1, a matrix is rank 2 **code-tensor.shape**
3. Axis or dimension-- A particular dimension of a tensor **code-tensor[0],tensor[:,1]**
4. size  -- The total number of items in the tensor **code-tf.size(tensor)**


In [ ]:
A.ndim

3

In [ ]:
#Creating a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
no_of_ele = 2*3*4*5
no_of_ele

120

In [ ]:
#Get various attributes of our attributes
print('Data of every element',rank_4_tensor.dtype)
print('Number of dimension',rank_4_tensor.ndim)
print('Shape of tensor',rank_4_tensor.shape)
print('Element along the 0 axis',rank_4_tensor.shape[0])
print("Elements along the last axis",rank_4_tensor.shape[-1])
print('Total number of elements in our tensor',tf.size(rank_4_tensor))
print('Total number of elements in our tensor',tf.size(rank_4_tensor).numpy())

Data of every element <dtype: 'float32'>
Number of dimension 4
Shape of tensor (2, 3, 4, 5)
Element along the 0 axis 2
Elements along the last axis 5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


## Indexing and expanding tensors
Tensors can be indexed just like python lists

Get the first elements of each dimension

In [ ]:
rank_4_tensor[0:2,0:2,0:2,0:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

Getting the first element from each dimension from each index except for the final one

In [ ]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

Creating a rank 2 tensor (2 dimensions)

In [ ]:
rank_2_tensor=tf.ones(shape=(2,2))

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
rank_2_tensor.ndim

2

In [ ]:
#Getting the last item of each row of the rank 2 tensor
rank_2_tensor[:-1,:-1]

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

Adding extra dimension to our rank 2 tensor

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

Alternative to tf.newaxis

In [ ]:
new_method = tf.expand_dims(rank_2_tensor,axis=-1) #-1 Means expand the final axis

In [ ]:
new_method

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1) #expand the 1 axis

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[1., 1.]],

       [[1., 1.]]], dtype=float32)>

## Manipulating tensors with basic operations

**Basic Operation**

In [ ]:
#You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Multiplication also work
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Subtraction of tensor
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#We can use the tensorflow built-in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor #No change in tensor values

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

## Matrix Multiplication - Part 1
In machine learning, matrix multiplication is one of the most common tensor operations
* Both matrices must be of the same type. The supported types are: bfloat16, float16, float32, float64, int32, int64, complex64, complex128.
* The inner dimensions must match
* The resulting matrix has the shape of the outer dimensions

In [ ]:
matrix1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
matrix1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
matrix2 = tf.constant([4,5,6,7,2,3],shape=[3,2])
matrix2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

In [ ]:
tf.matmul(matrix1,matrix2) #Matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [58, 73]], dtype=int32)>

In [ ]:
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:
mul = tf.matmul(a,b)
mul

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]], dtype=int32)>

**tf.matmul()** attributes
1. **transpose_a**	If True, a is transposed before multiplication.
2. **transpose_b**  If True, b is transposed before multiplication.
3. **adjoint_a**    If True, a is conjugated and transposed before multiplication. 
4. **adjoint_b**    If True, b is conjugated and transposed before multiplication.

In [ ]:
#Matrix Multiplication with python operator "@"
c=a@b

In [ ]:
c.shape

TensorShape([2, 2, 2])

## Matrix Multiplication - Part 2

In [ ]:
x = tf.constant([[1,2,3],
                 [8,9,4]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [8, 9, 4]], dtype=int32)>

In [ ]:
y = tf.constant([[0,1,3],
                 [6,9,5]])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 3],
       [6, 9, 5]], dtype=int32)>

In [ ]:
#tf.matmul(x,y)

In [ ]:
#Let's change the shape of y
y=tf.reshape(y,shape=[3,2])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [3, 6],
       [9, 5]], dtype=int32)>

In [ ]:
#Try to multiply x by reshaped y
x @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[33, 28],
       [63, 82]], dtype=int32)>

In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[33, 28],
       [63, 82]], dtype=int32)>

## Matrix Multiplication - Part 3
**The dot product**
Matrix multiplication is also referred to as the dot product.
We can Perform matrix multiplication using:-
* 'tf.matmul()'
* 'tf.tensordot()'

In [ ]:
x,y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [8, 9, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 1],
        [3, 6],
        [9, 5]], dtype=int32)>)

In [ ]:
#Perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x),tf.transpose(y),axes=1) #axes = 1 means for matrix multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8, 51, 49],
       [ 9, 60, 63],
       [ 4, 33, 47]], dtype=int32)>

In [ ]:
tf.transpose(y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 3, 9],
       [1, 6, 5]], dtype=int32)>

In [ ]:
print('Normal y:')
print(y,'\n')
print("y reshaped to (2,3):")
print(tf.reshape(y,shape=(2,3)),"\n")
print("y transposed ")
print(tf.transpose(y))

Normal y:
tf.Tensor(
[[0 1]
 [3 6]
 [9 5]], shape=(3, 2), dtype=int32) 

y reshaped to (2,3):
tf.Tensor(
[[0 1 3]
 [6 9 5]], shape=(2, 3), dtype=int32) 

y transposed 
tf.Tensor(
[[0 3 9]
 [1 6 5]], shape=(2, 3), dtype=int32)


## Changing the datatype of a tensor

In [ ]:
#Create a new tensor with default datatype (float32)
b = tf.constant([1.7,7.4])
b.dtype

tf.float32

In [ ]:
c = tf.constant([7,10])
c.dtype

tf.int32

In [ ]:
# Change from float32 to float16(Reduced)
b= tf.cast(b,dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
#Changes from float32 to float16 (Reduced Precision)
d = tf.cast(b,dtype=tf.float32)
d

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7001953, 7.3984375], dtype=float32)>

## Aggregating Tensors
Aggregating tensors = Condensing them from multiple values down to a smaller amount of values

In [ ]:
#Get the absolute values
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
compl = tf.constant([[-4 + 3j], [-3 + 4j]])
tf.abs(compl)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.],
       [5.]])>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
np.random.seed(42)
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37,  1, 63, 59, 20, 32, 75, 57, 21, 88, 48, 90, 58, 41, 91,
       59, 79, 14, 61, 61, 46, 61, 50, 54, 63,  2, 50,  6, 20, 72, 38])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2542>

**Exercise**-- With what we've just learned, find the variance and standard deviation of our 'E' tensor using TensorFlow methods.

In [ ]:
import tensorflow_probability as tfp
#Find the variance
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=776>

In [ ]:
#Find the standard Deviation
tf.math.reduce_std(tf.cast(E,dtype='float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=27.849854>

## Find the positional maximum and minimum

In [ ]:
#Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Check for equality
f[tf.argmax(f)] == tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
assert f[tf.argmax(f)] == tf.reduce_max(f)

In [ ]:
#Finding the minimum
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
assert tf.reduce_min(f) == f[tf.argmin(f)]

## Squeezing a tensor (removing all 1-dimension axes)

In [ ]:
#Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## One HOT Encoding 

In [ ]:
#Create a list of indices
some_list = [0,1,2,3] #red, green, blue, purple
#One hot encode our list of indices
tf.one_hot(some_list,depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

The locations represented by indices in indices take value on_value, while all other locations take value off_value

In [ ]:
#Specity custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value='yo i love deep learning',off_value="I also like to dance")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo i love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo i love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo i love deep learning']],
      dtype=object)>

## Squaring, log, Square Root

In [ ]:
#Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square It
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.math.sqrt(tf.cast(H,dtype='float32'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
#Find the log of tensor
tf.math.log(tf.cast(H,dtype='float32'))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Exploring Tensorflow and Numpy compatibility
TensorFlow interacts beautifully with NumPy arrays
* One of the main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU for faster Numerical Processing.

In [40]:
#Create a tensor directly with NumPy arrays
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [41]:
#Convert our tensor back to the numpy arrays
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [42]:
#Convert tensor J to a Numpy array
J.numpy(),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [43]:
#Convert tensor J to NumPy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [44]:
#The default types of each are slightly different 
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
#check the datatypes of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

## Making Sure our tensor operations run really fast on GPUs
* Finding accessing to GPU

In [14]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [15]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [16]:
!nvidia-smi

Tue Jul 13 12:13:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0    75W / 149W |    124MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

If we have access to a CUDA-enabled GPU. Tensorflow will automatically will automatically use it whenever possible. 